### ISSUE TITLE
This is not correct negative longitude values

### ISSUE THREAD

**Issue by ricardo88faria** [dongqi-DQ/WRF4PALM#1] opened 2021-10-25 11:20 UTC
This line is not compatible with negative longitude values, absolute difference index value should be used instead.

https://github.com/dongqi-DQ/WRF4PALM/blob/2498cc15e7639e54204cff9b0bd7a23d8de17112/run_config_wrf4palm.py#L229

**Comment by dongqi-DQ** [comment] 2021-10-26 09:42
Thanks for reporting this. Sorry I didn't consider this before. I've updated the code to swap the west and east indices in case negative longitude values are used. 

I did not use the absolute value here because if east_idx<west_idx, then xarray may not be able to crop the correct area from the WRF output later in the code.

I will leave this issue open just in case the recent update does not fix the problem.

Edit:
After a few tests, I found the problem may be caused by the `loc_dom` function. It was not compatible with wgs84 projection, and this has been fixed. `loc_dom` will use UTM projection to calculate lat/lon at the lateral boundaries.

**Comment by ricardo88faria** [comment] 2021-10-27 09:13
I think you also missed the negative latitudes.
Edit:
Undo the code to swap the west and east indices in case negative longitude values are used.

**Comment by dongqi-DQ** [comment] 2021-10-27 09:25
> I think you also missed the negative latitudes. Edit: Undo the code to swap the west and east indices in case negative longitude values are used.

This should be compatible with negative latitudes as it has been tested over New Zealand domains. I also tested it over a Brazil domain (both lats and lons are negative). The nearest functions should not be affected by negative latitudes/longitudes when the projection of WRF is used directly or the projection given by the user is correct. 

The [nearest functions](https://github.com/dongqi-DQ/WRF4PALM/blob/v1.1/dynamic_util/nearest.py) calculate the absolute values of [`array-number`](https://github.com/dongqi-DQ/WRF4PALM/blob/v1.1/dynamic_util/nearest.py#L25) rather than the difference between the absolute values of `array` and `number`. 

If you still have problems running wrf4palm v1.1, is it possible for you to share the namelist and WRF output you used? 

Thanks

**Comment by dongqi-DQ** [comment] 2021-10-27 20:34
I will leave the swap indices code there until further tests are implemented. The if statement will not be triggered unless there is something wrong with the projection given by users.

**Comment by dongqi-DQ** [comment] 2023-07-27 22:52
The latitudes and longitudes should be correct now. I will close this issue.

**Closed as completed by dongqi-DQ** 2023-07-27 22:52 UTC
Labels: good first issue
