### ISSUE TITLE
ValueError: output array is read-only

### ISSUE THREAD

**Issue by liqy233** [dongqi-DQ/WRF4PALM#23] opened 2023-04-11 14:27 UTC
Hello! When I was running, an error was reported with the following information：

(lqy) lqy@LAPTOP-RACVSMSQ:/mnt/d/dynamic$ python create_dynamic.py
Loading WRF netCDF: wrf_output/wrfout_d01_lqy_test.nc
WRF output reading done.
Interpolating horizontal fields...
100%|#########################################################################################| 3/3 [00:53<00:00, 17.80s/it]
Done.
Interpolating unstaggered vertical levels: 33it [03:47, 6.89s/it]
Interpolating staggered vertical levels: 32it [00:41, 1.31s/it]

Vertical interpolation done.
Resolving surface NaNs: 100%|#################################################################| 3/3 [00:36<00:00, 12.12s/it]

Calculating soil temperature and moisture from WRF
Traceback (most recent call last):
File "create_dynamic.py", line 407, in <module>
init_soil_tmn = np.nanmean(np.ma.masked_where(landmask == 0, tmn))
File "<__array_function__ internals>", line 5, in nanmean
File "/home/lqy/anaconda3/envs/lqy/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 952, in nanmean
avg = _divide_by_count(tot, cnt, out=out)
File "/home/lqy/anaconda3/envs/lqy/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 214, in _divide_by_count
return np.divide(a, b, out=a, casting='unsafe')
ValueError: output array is read-only

Could you please provide me some helps?
I didn't change anything except  you told before in the readme.txt

**Comment by dongqi-DQ** [comment] 2023-04-11 21:25
Hi, 

From the command you provided, I'm suspecting that you're using v1.0 of WRF4PALM. Can you please try the latest version of WRF4PALM (v1.1_beta)? The first version has several bugs and I believe most of the issues should be fixed after our latest modification.  

Just a note - the `ValueError` could be due to non-contiguous memory caused by some incompatibility between the underlying Python code and Numpy.  See these two links for more info:
https://github.com/seanbell/intrinsic/issues/5
http://claytonturner.blogspot.com/2015/06/numpy-valueerror-output-array-is-read.html

**Comment by dongqi-DQ** [comment] 2023-07-27 22:54
I would take that this issue is solved since it has been inactive for over 3 months. I will close this ticket for now. But feel free to reopen it if the problem is not solved.

**Closed as completed by dongqi-DQ** 2023-07-27 22:54 UTC

**Comment by liqy233** [comment] 2023-09-15 12:27
Thanks!!!!!!!!
I only noticed this news today，sorry~
